# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160915_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_proposed', models.DateTimeField(auto_now_add=True)),
                ('date_confirmed', models.DateTimeField(null=True)),
                ('date_rejected', models.DateTimeField(null=True)),
                ('reason_rejected', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='_paired_with',
        ),
        migrations.AddField(
            model_name='profile',
            name='_paired_with',
            field=models.ManyToManyField(null=True, related_name='_profile__paired_with_+', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='pairproposal',
            name='from_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_pair', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='pairproposal',
            name='to_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_pair', to='users.Profile'),
        ),
    ]
