# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160915_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairproposal',
            name='from_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_made', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='pairproposal',
            name='to_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_received', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='_paired_with',
            field=models.ManyToManyField(related_name='_profile__paired_with_+', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_profile_friends_+', to='users.Profile'),
        ),
    ]
