# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160916_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
