# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160920_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='second_candidate',
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_candidate',
            field=models.CharField(choices=[('Clinton', 'Clinton'), ('Johnson', 'Johnson')], max_length=255, null=True),
        ),
    ]
