# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_users-profile-encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairproposal',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
