# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-02 03:45
from __future__ import unicode_literals

from django.db import migrations


def encode_reason(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    for profile in Profile.objects.all():
        profile.clean()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_pairproposal_ref_id'),
    ]

    operations = [
        migrations.RunPython(encode_reason),
    ]
