# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-02 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20161002_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='_paired_with',
            field=models.ManyToManyField(blank=True, related_name='_profile__paired_with_+', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_candidate',
            field=models.CharField(choices=[('Clinton', 'Clinton'), ('Johnson', 'Johnson'), ('Stein', 'Stein')], max_length=255, null=True),
        ),
    ]
