# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-19 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_signuplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_random',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_candidate',
            field=models.CharField(choices=[('Clinton', 'Hillary Clinton'), ('Johnson', 'Gary Johnson'), ('Stein', 'Jill Stein')], max_length=255, null=True),
        ),
    ]
